### ISSUE TITLE
Use `dataTransfer` for insertReplacementText input events

### ISSUE THREAD

**Issue by adamsanderson** [evolu-io/evolu#53]
Not an issue so much as a tip from a stranger ;)

A friend starred your project so I decided to see how you've implemented various interactions with `beforeInput` events and noticed that you're backing into the value of `insertReplacementText` events:
https://github.com/steida/slad/blob/f6dd226da225db035db45337243fec67ad643238/packages/slad/hooks/useBeforeInput.ts#L164-L169

Per the spec, and even in practice, I've found that you can get either a `text/plain` or `text/html` representation from the `dataTransfer` property.
https://www.w3.org/TR/input-events-1/#overview

So there's a good chance that you can get the value you want by using:
```
  const text = event.dataTransfer. getData('text/plain');
```

**Comment by steida** [comment]
@adamsanderson Thank you! Check current implementation. I decided to let browsers do their things and then read from DOM and override it. Do you think it ok?

**Comment by adamsanderson** [comment]
It should, though browsers are mysterious beasts.

**Comment by steida** [comment]
Actually, I am probably going to normalize whitespaces, so, it should be possible to use dataTransfer, but, not preventDefault typing should lead to better performance, so I will probably leave it as is.

https://github.com/facebook/draft-js/blob/dceddf552006ea607bc5c15ce3d1b629eca1cb70/src/component/handlers/edit/editOnBeforeInput.js
